### ISSUE TITLE
Chem Plant kubejs plant casing condition crashes minecraft

### ISSUE THREAD

**Issue by mordgren** [Arborsm/ArborCore#19]
Is it able to make new chem plant recepies via kubejs ?
There is no(or i cant find how to set plant casing) condition,so when i dont set it recepie shows in jei but when trying to craft it in chem plant game crashes, would be very apreciateful if you say how to do it in kubejs. 
Here`s code and crashlog
ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_plant('e85_fuel')
    .inputFluids(
        'gtceu:ethanol 17050',
        'gtceu:light_fuel 3000',
        'gtceu:butene 50'
    )
    .outputFluids('gtceu:e85_fuel 20000')
    .duration(60)
    .EUt(480)
}
)

**Comment by mordgren** [comment]
[Uploading latest.log…]()
[Uploading debug.log…]()

**Comment by mordgren** [comment]
[18Jul2024 00:37:51.620] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at dev.arbor.gtnn.api.machine.multiblock.ChemicalPlantMachine$Companion.chemicalPlantRecipe(ChemicalPlantMachine.kt:94) ~[gtnn-1.0.8b.jar%23289!/:?]
	at com.gregtechceu.gtceu.api.machine.multiblock.WorkableMultiblockMachine.getRealRecipe(WorkableMultiblockMachine.java:202) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.multiblock.WorkableMultiblockMachine.doModifyRecipe(WorkableMultiblockMachine.java:197) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.feature.IRecipeLogicMachine.fullModifyRecipe(IRecipeLogicMachine.java:54) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.checkMatchedRecipeAvailable(RecipeLogic.java:214) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.handleSearchingRecipes(RecipeLogic.java:303) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.findAndHandleRecipe(RecipeLogic.java:292) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.serverTick(RecipeLogic.java:184) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.TickableSubscription.run(TickableSubscription.java:23) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.MetaMachine.executeTick(MetaMachine.java:286) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.machine.MetaMachine.serverTick(MetaMachine.java:258) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at com.gregtechceu.gtceu.api.block.IMachineBlock.lambda$getTicker$0(IMachineBlock.java:66) ~[gtceu-1.20.1-1.3.0-a.jar%23288!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?]
	... 5 more
