### ISSUE TITLE
最新版格雷不兼容

### ISSUE THREAD

**Issue by 1luik** [Arborsm/ArborCore#22]
最新版格雷不兼容
格雷版本 1.20.1-1.3.1-build_920
报错

[11:06:47] [main/FATAL] [mixin/]: Mixin prepare for mod gtnn failed preparing gt.FluidStorageMixin in gtnn.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Mixin target type mismatch: com.gregtechceu.gtceu.api.fluids.store.FluidStorage is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@37d43b9b
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: com.gregtechceu.gtceu.api.fluids.store.FluidStorage is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@37d43b9b
        at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442%23445!/:0.12.11+mixin.0.8.5] {}
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2365!/:?] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar%2355!/:10.0.9+10.0.9+main.dcd20f30] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at java.lang.Class.forName0(Native Method) ~[?:?] {}
        at java.lang.Class.forName(Class.java:534) ~[?:?] {}
        at java.lang.Class.forName(Class.java:513) ~[?:?] {}
        at org.sinytra.connector.service.ConnectorLoaderService$1.lambda$updateModuleReads$0(ConnectorLoaderService.java:65) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442!/:1.0.0-beta.44+1.20.1] {}
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95) ~[modlauncher-10.0.9.jar%2355!/:10.0.9+10.0.9+main.dcd20f30] {}
        at org.sinytra.connector.service.ConnectorLoaderService$1.updateModuleReads(ConnectorLoaderService.java:65) ~[%5B信雅互联%5DConnector-1.0.0-beta.44+1.20.1.jar%23442!/:1.0.0-beta.44+1.20.1] {}
        at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.1-47.2.18.jar%2369!/:1.0] {}
        at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.1-47.2.18.jar%2369!/:1.0] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92) ~[fmlloader-1.20.1-47.2.18.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Exception in thread "main" java.lang.RuntimeException: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [gtnn.mixins.json:gt.FluidStorageMixin from mod gtnn] from phase [DEFAULT] in config [gtnn.mixins.json] FAILED during PREPARE
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [gtnn.mixins.json:gt.FluidStorageMixin from mod gtnn] from phase [DEFAULT] in config [gtnn.mixins.json] FAILED during PREPARE
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at LAYER SERVICE/org.sinytra.connector@1.0.0-beta.44+1.20.1/org.sinytra.connector.service.ConnectorLoaderService$1.lambda$updateModuleReads$0(ConnectorLoaderService.java:65)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at LAYER SERVICE/org.sinytra.connector@1.0.0-beta.44+1.20.1/org.sinytra.connector.service.ConnectorLoaderService$1.updateModuleReads(ConnectorLoaderService.java:65)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: com.gregtechceu.gtceu.api.fluids.store.FluidStorage is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@37d43b9b
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
        ... 33 more
[11:06:27] [WARN] [FabricLoader/Resolution]: Warnings were found!
 - §Emod 'Alloy Forgery' (alloy_forgery)§r 2.1.2+1.20 recommends version 12.0.0 or later of §6roughlyenoughitems§r, which is missing!
         - You should install version 12.0.0 or later of §6roughlyenoughitems§r for the optimal experience.

**Comment by Arborsm** [comment]
无法复现

**Comment by 1luik** [comment]
> 无法复现

你加信雅互联了吗

**Comment by 1luik** [comment]
> > 无法复现
> 
> 你加信雅互联了吗

可能是我的信雅互联mixin炸了

**Comment by Arborsm** [comment]
其他模组的问题

**Comment by 1luik** [comment]
是你没有使用最新版

**Comment by 1luik** [comment]
我用的是今天刚更新的格雷

**Comment by 1luik** [comment]
她吧FluidStorage改成interface了

**Comment by 1luik** [comment]
> 其他模组的问题
他们吧这个版本删除了，我给你我的那个
[[格雷科技现代版]gtceu-1.20.1-1.3.1-build_920.jar.zip](https://github.com/user-attachments/files/16491403/gtceu-1.20.1-1.3.1-build_920.jar.zip)

[Uploading [格雷科技现代版]gtceu-1.20.1-1.3.1-build_920.jar…]()

**Comment by Arborsm** [comment]
build不做兼容，发release才做

**Comment by 1luik** [comment]
> > 其他模组的问题
> > 他们吧这个版本删除了，我给你我的那个
> > [[格雷科技现代版]gtceu-1.20.1-1.3.1-build_920.jar.zip](https://github.com/user-attachments/files/16491403/gtceu-1.20.1-1.3.1-build_920.jar.zip)
> 
> Uploading [格雷科技现代版]gtceu-1.20.1-1.3.1-build_920.jar…

他们没删是我访问成1.21 920了

**Comment by 1luik** [comment]
> build不做兼容，发release才做

吧
FluidStorage改成com.gregtechceu.gtceu.api.fluids.store.FluidStorageImpl就可以了

**Comment by 1luik** [comment]
[gtnn-1.0.8c.jar.修改版.zip](https://github.com/user-attachments/files/16499765/gtnn-1.0.8c.jar.zip)
[dev.zip](https://github.com/user-attachments/files/16499785/dev.zip)
