### ISSUE TITLE
GTCEu breaking change on LDLib dependency

### ISSUE THREAD

**Issue by Telmooo** [Arborsm/ArborCore#29]
With the most recent update of GTCEu, GT-- no longer loads correctly due to breaking changes on the way Items and Fluids are handled.

See [here](https://github.com/GregTechCEu/GregTech-Modern/pull/1975) and [here](https://github.com/GregTechCEu/GregTech-Modern/pull/2246).

Relevant stacktrace

```
	Failure message: GT-- (gtnn) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'void com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty.<init>(int, com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty$GasTier, int, int)'
	Mod Version: 1.1.4
	Mod Issue URL: https://github.com/Arborsm/GT--/issues
	Exception message: java.lang.NoSuchMethodError: 'void com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty.<init>(int, com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty$GasTier, int, int)'
Stacktrace:
	at dev.arbor.gtnn.data.materials.AdjustGTMaterials.init(AdjustGTMaterials.kt:18) ~[gtnn-1.1.4.jar%23159!/:?] {re:classloading}
	at dev.arbor.gtnn.data.GTNNMaterials.init(GTNNMaterials.java:147) ~[gtnn-1.1.4.jar%23159!/:?] {re:classloading}
	at dev.arbor.gtnn.GTNNRegistries.registerMaterials(GTNNRegistries.kt:49) ~[gtnn-1.1.4.jar%23159!/:?] {re:classloading,re:mixin}

...

	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		configuration-forge-1.20.1-2.2.0.jar              |Configuration                 |configuration                 |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.11-universal.jar                |Forge                         |forge                         |47.3.11             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ldlib-forge-1.20.1-1.0.31.jar                     |LowDragLib                    |ldlib                         |1.0.31              |COMMON_SET|Manifest: NOSIGNATURE
		gtnn-1.1.4.jar                                    |GT--                          |gtnn                          |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		gtceu-1.20.1-1.5.0.jar                            |GregTech                      |gtceu                         |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
```

**Comment by Arborsm** [comment]
done
