### ISSUE TITLE
crash with gtm 1.2.1

### ISSUE THREAD

**Issue by jmoiron** [Arborsm/ArborCore#9]
gtnn crashes on startup w/ gtceu modern 1.2.1

```
...
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassCastException: class com.gregtechceu.gtceu.common.data.GTRecipeModifiers$ElectricOverclockModifier cannot be cast to class java.util.function.BiFunction (com.gregtechceu.gtceu.common.data.GTRecipeModifiers$ElectricOverclockModifier is in module gtceu@1.2.1 of loader 'TRANSFORMER' @5b8853; java.util.function.BiFunction is in module java.base of loader 'bootstrap')
	at TRANSFORMER/gtnn@1.0.5/org.arbor.gtnn.data.GTNNMachines.lambda$registerSimpleMachines$14(GTNNMachines.java:295)
	at TRANSFORMER/gtnn@1.0.5/org.arbor.gtnn.data.GTNNMachines.registerTieredMachines(GTNNMachines.java:281)
	at TRANSFORMER/gtnn@1.0.5/org.arbor.gtnn.data.GTNNMachines.registerSimpleMachines(GTNNMachines.java:290)
	at TRANSFORMER/gtnn@1.0.5/org.arbor.gtnn.data.GTNNMachines.<clinit>(GTNNMachines.java:101)
```

**Comment by jmoiron** [comment]
Looks like it is probably this change https://github.com/GregTechCEu/GregTech-Modern/commit/c78c14e6b8ff8451bbc0eff055144f7f572d6d6a

**Comment by Arborsm** [comment]
fixed
